"""cv analyses

Revision ID: 0004_cv_analyses
Revises: 0003_rls_deny_by_default
Create Date: 2026-07-27 10:37:52.790193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004_cv_analyses'
down_revision: Union[str, Sequence[str], None] = '0003_rls_deny_by_default'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_analyses',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('skills_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_analyses_profile_id'), 'cv_analyses', ['profile_id'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate does not know about RLS. Without this the table would be
    # the one hole in an otherwise deny-by-default schema — and it holds the
    # most personal data in the product.
    op.execute("ALTER TABLE public.cv_analyses ENABLE ROW LEVEL SECURITY")
    op.execute("REVOKE ALL ON public.cv_analyses FROM anon")
    op.execute("REVOKE ALL ON public.cv_analyses FROM authenticated")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("GRANT ALL ON public.cv_analyses TO anon")
    op.execute("GRANT ALL ON public.cv_analyses TO authenticated")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_analyses_profile_id'), table_name='cv_analyses')
    op.drop_table('cv_analyses')
    # ### end Alembic commands ###
