"""matching tables

Revision ID: 0005_matching
Revises: 0004_cv_analyses
Create Date: 2026-07-27 10:53:13.145755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005_matching'
down_revision: Union[str, Sequence[str], None] = '0004_cv_analyses'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_profile_id'), 'job_matches', ['profile_id'], unique=False)
    op.create_table('resume_optimizations',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('ats_score_before', sa.Integer(), nullable=False),
    sa.Column('ats_score_after', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_optimizations_profile_id'), 'resume_optimizations', ['profile_id'], unique=False)
    op.create_table('skill_gap_analyses',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('overall_gap_score', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_analyses_profile_id'), 'skill_gap_analyses', ['profile_id'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate does not know about RLS. Every table in this schema is
    # deny-by-default; these three hold pasted job descriptions and CV
    # rewrites. tests/test_migrations.py fails the build if this is skipped.
    for table in ("job_matches", "skill_gap_analyses", "resume_optimizations"):
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"REVOKE ALL ON public.{table} FROM anon")
        op.execute(f"REVOKE ALL ON public.{table} FROM authenticated")


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("job_matches", "skill_gap_analyses", "resume_optimizations"):
        op.execute(f"GRANT ALL ON public.{table} TO anon")
        op.execute(f"GRANT ALL ON public.{table} TO authenticated")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_gap_analyses_profile_id'), table_name='skill_gap_analyses')
    op.drop_table('skill_gap_analyses')
    op.drop_index(op.f('ix_resume_optimizations_profile_id'), table_name='resume_optimizations')
    op.drop_table('resume_optimizations')
    op.drop_index(op.f('ix_job_matches_profile_id'), table_name='job_matches')
    op.drop_table('job_matches')
    # ### end Alembic commands ###
