"""roadmaps

Revision ID: 0006_roadmap
Revises: 0005_matching
Create Date: 2026-07-27 11:11:05.326862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006_roadmap'
down_revision: Union[str, Sequence[str], None] = '0005_matching'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('total_estimated_months', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_profile_id'), 'roadmaps', ['profile_id'], unique=False)
    op.create_table('roadmap_steps',
    sa.Column('roadmap_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skills_to_acquire', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('prerequisite_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('estimated_months', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='todo', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_steps_profile_id'), 'roadmap_steps', ['profile_id'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_roadmap_id'), 'roadmap_steps', ['roadmap_id'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate does not know about RLS. app/security.py plus
    # tests/test_migrations.py fail the build if a table is left out.
    for table in ("roadmaps", "roadmap_steps"):
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"REVOKE ALL ON public.{table} FROM anon")
        op.execute(f"REVOKE ALL ON public.{table} FROM authenticated")


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("roadmaps", "roadmap_steps"):
        op.execute(f"GRANT ALL ON public.{table} TO anon")
        op.execute(f"GRANT ALL ON public.{table} TO authenticated")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_steps_roadmap_id'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_profile_id'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_index(op.f('ix_roadmaps_profile_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
