"""interview sessions

Revision ID: 0007_interview
Revises: 0006_roadmap
Create Date: 2026-07-27 11:27:56.721954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007_interview'
down_revision: Union[str, Sequence[str], None] = '0006_roadmap'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('interviewer_name', sa.String(length=120), nullable=True),
    sa.Column('cv_text', sa.Text(), nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('final_evaluation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_profile_id'), 'interview_sessions', ['profile_id'], unique=False)
    op.create_table('interview_turns',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('expected_topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('feedback', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_turns_profile_id'), 'interview_turns', ['profile_id'], unique=False)
    op.create_index(op.f('ix_interview_turns_session_id'), 'interview_turns', ['session_id'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate does not know about RLS. These hold interview transcripts,
    # which are as personal as the CV itself.
    for table in ("interview_sessions", "interview_turns"):
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"REVOKE ALL ON public.{table} FROM anon")
        op.execute(f"REVOKE ALL ON public.{table} FROM authenticated")


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("interview_sessions", "interview_turns"):
        op.execute(f"GRANT ALL ON public.{table} TO anon")
        op.execute(f"GRANT ALL ON public.{table} TO authenticated")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_turns_session_id'), table_name='interview_turns')
    op.drop_index(op.f('ix_interview_turns_profile_id'), table_name='interview_turns')
    op.drop_table('interview_turns')
    op.drop_index(op.f('ix_interview_sessions_profile_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
