"""chat and rag corpus

Revision ID: 0008_rag
Revises: 0007_interview
Create Date: 2026-07-27 11:41:57.264638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Autogenerate renders the column as pgvector.sqlalchemy.vector.VECTOR(...)
# but does not emit the import for it, so the migration fails with a
# NameError. Alembic has no hook that fixes this for us.
import pgvector.sqlalchemy  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '0008_rag'
down_revision: Union[str, Sequence[str], None] = '0007_interview'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_profile_created', 'chat_messages', ['profile_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_profile_id'), 'documents', ['profile_id'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_profile_id'), 'document_chunks', ['profile_id'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate does not emit vector indexes. Without this, every chat turn
    # sequentially scans and re-computes distance for every chunk in the table.
    #
    # HNSW rather than ivfflat: it needs no `lists` tuning against a corpus
    # size we cannot predict, and it does not degrade when the table is still
    # nearly empty -- which it is on day one. Cosine ops because the vectors
    # are L2-normalized at write time.
    op.execute(
        "CREATE INDEX ix_document_chunks_embedding_hnsw "
        "ON public.document_chunks USING hnsw (embedding vector_cosine_ops)"
    )

    for table in ("chat_messages", "documents", "document_chunks"):
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"REVOKE ALL ON public.{table} FROM anon")
        op.execute(f"REVOKE ALL ON public.{table} FROM authenticated")


def downgrade() -> None:
    """Downgrade schema."""
    for table in ("chat_messages", "documents", "document_chunks"):
        op.execute(f"GRANT ALL ON public.{table} TO anon")
        op.execute(f"GRANT ALL ON public.{table} TO authenticated")
    op.execute("DROP INDEX IF EXISTS public.ix_document_chunks_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_profile_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_profile_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_chat_messages_profile_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
