"""chat message position

Ordering chat turns by created_at is unsound: func.now() is transaction start
time in Postgres, so a question and the reply written alongside it in the same
transaction carry identical timestamps, and the UUIDv4 primary key breaks no
ties. This adds the explicit order the conversation always had implicitly.

Hand-written rather than autogenerated: the backfill below needs a window
function, which autogenerate cannot infer.

Revision ID: 0009_chat_position
Revises: 0008_rag
Create Date: 2026-07-27

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0009_chat_position'
down_revision: Union[str, Sequence[str], None] = '0008_rag'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'chat_messages',
        sa.Column(
            'position', sa.Integer(), nullable=False, server_default='0'
        ),
    )

    # Backfill existing conversations. Ties on created_at are resolved by
    # putting the user's turn first, which is the only order that can be
    # correct for a question and its own answer.
    op.execute(
        """
        UPDATE chat_messages AS m
        SET position = ordered.seq
        FROM (
            SELECT
                id,
                ROW_NUMBER() OVER (
                    PARTITION BY profile_id
                    ORDER BY created_at, CASE role WHEN 'user' THEN 0 ELSE 1 END
                ) - 1 AS seq
            FROM chat_messages
        ) AS ordered
        WHERE m.id = ordered.id
        """
    )

    op.create_index(
        'ix_chat_messages_profile_position',
        'chat_messages',
        ['profile_id', 'position'],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_chat_messages_profile_position', table_name='chat_messages')
    op.drop_column('chat_messages', 'position')
