"""richer roadmap steps and the curated knowledge corpus

Two changes that ship together because both come from the same pass over the
AI layer.

1. Roadmap steps gained the fields that make a step actionable rather than a
   label: why it comes here, how hard it is for this person, hours per week,
   resources, and a project. All are NOT NULL with a server default so the
   backfill of existing rows is the default itself — an older roadmap keeps
   rendering, with the new fields empty.

2. `knowledge_chunks` holds the curated `knowledge_base/` corpus. It has no
   `profile_id` because it belongs to nobody: it is editorial content the team
   maintains, identical for every user, written only by the ingest CLI. RLS is
   still applied — the browser's public key must read nothing regardless of
   whether the content is sensitive.

Hand-written rather than autogenerated: the HNSW index below is invisible to
autogenerate, and the ALTER/REVOKE statements always are.

Revision ID: 0010_knowledge
Revises: 0009_chat_position
Create Date: 2026-07-28

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Autogenerate renders vector columns without emitting this import, which
# fails at runtime with a NameError. See 0008.
import pgvector.sqlalchemy  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '0010_knowledge'
down_revision: Union[str, Sequence[str], None] = '0009_chat_position'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_JSON = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql')

_NEW_STEP_COLUMNS = (
    'reason',
    'difficulty',
    'recommended_resources',
    'project_to_practice',
    'estimated_weekly_hours',
)


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'roadmap_steps',
        sa.Column('reason', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'roadmap_steps',
        sa.Column(
            'difficulty',
            sa.String(length=20),
            nullable=False,
            server_default='Intermediate',
        ),
    )
    op.add_column(
        'roadmap_steps',
        sa.Column(
            'recommended_resources', _JSON, nullable=False, server_default='[]'
        ),
    )
    op.add_column(
        'roadmap_steps',
        sa.Column('project_to_practice', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'roadmap_steps',
        sa.Column(
            'estimated_weekly_hours',
            sa.Numeric(precision=4, scale=1),
            nullable=False,
            server_default='0',
        ),
    )

    op.create_table(
        'knowledge_chunks',
        sa.Column('category', sa.String(length=80), nullable=False),
        sa.Column('source', sa.String(length=300), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=300), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('content_hash', sa.String(length=64), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source', 'chunk_index', name='uq_knowledge_chunks_source_idx'),
    )
    op.create_index(
        'ix_knowledge_chunks_category', 'knowledge_chunks', ['category'], unique=False
    )
    # Same reasoning as document_chunks in 0008: HNSW needs no `lists` tuning,
    # does not degrade on a nearly-empty table, and cosine ops match the
    # L2-normalized vectors written by app.ai.embeddings.
    op.execute(
        "CREATE INDEX ix_knowledge_chunks_embedding_hnsw "
        "ON public.knowledge_chunks USING hnsw (embedding vector_cosine_ops)"
    )

    op.execute("ALTER TABLE public.knowledge_chunks ENABLE ROW LEVEL SECURITY")
    op.execute("REVOKE ALL ON public.knowledge_chunks FROM anon")
    op.execute("REVOKE ALL ON public.knowledge_chunks FROM authenticated")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("GRANT ALL ON public.knowledge_chunks TO anon")
    op.execute("GRANT ALL ON public.knowledge_chunks TO authenticated")
    op.execute("DROP INDEX IF EXISTS public.ix_knowledge_chunks_embedding_hnsw")
    op.drop_index('ix_knowledge_chunks_category', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')

    for column in reversed(_NEW_STEP_COLUMNS):
        op.drop_column('roadmap_steps', column)
